development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:baf2d770f76268ccfa11a31899c5ed87@tarpon.redistogo.com:11879/
  channel_prefix: chat_app_production

